### ISSUE TITLE
Results Page- Share Results/Share Poll, Create New button

### ISSUE THREAD

**Issue by rosenbergmichael** [chingu-voyages/v30-geckos-team-08#37]
-Under pie chart, "share these reults" link with pop up that displays URL for sharing, also social icons for sharing (Facebook, Twitter, Reddit, LinkedIn)
-Same thing for Share Poll
-Create button "Create New Poll" that takes user back to home page

**Comment by shepherdlewis000** [comment]
Need to properly embed OG OpenGraph metatags for respective poll, maybe a picture of a generic pie graph 

How StrawPoll.com does shares of poll
Icons across bottom with these links

https://api.whatsapp.com/send?text=What%20is%20the%20best%20color%20out%20of%20these%20options?%20-%20https://strawpoll.com/dg9kp6ser

https://telegram.me/share/url?text=What%20is%20the%20best%20color%20out%20of%20these%20options?&url=https://strawpoll.com/dg9kp6ser

https://www.reddit.com/submit?url=https://strawpoll.com/dg9kp6ser&title=What%20is%20the%20best%20color%20out%20of%20these%20options?

http://www.twitter.com/share?text=What%20is%20the%20best%20color%20out%20of%20these%20options?&url=https://strawpoll.com/dg9kp6ser

https://www.facebook.com/sharer/sharer.php?u=https://strawpoll.com/dg9kp6ser

Final icon is an embed symbol </> which opens modal giving this text and link
Use the code below to embed this poll on any website.
The height and width of the widget were calculated automatically. If necessary, you can change the width and height in the code according to your needs. 

<iframe width="620" height="480" src="https://strawpoll.com/embed/dg9kp6ser" style="width: 100%; height: 480px;" frameborder="0" allowfullscreen></iframe>

What's returned is just the poll on a page without banner etc.
