### ISSUE TITLE
Style/Responsive

### ISSUE THREAD

**Issue by rosenbergmichael** [chingu-voyages/v30-geckos-team-08#42]
-After each page/component, add styling, responsive media queries
-White/offwhite backdrop, blue-ish accents/highlights
-https://fonts.google.com/specimen/Poppins

**Comment by shepherdlewis000** [comment]
I've been working on input poll form and needed to pick out some colors, so I grabbed this "color pallete" or "color scheme" from somewhere. 
![website-1024x512.jpg](https://images.zenhubusercontent.com/5ffb3867037534480b8094ae/46f8ec63-8b62-47d9-860e-d3ccb51e0bf7)

#E27D60 reddish brown
#85DCB a blue approaching aqua
#EBA87C I lightish tan
#C38D9E a soft muted purple
 #41B3A3 a darker aquaish

**Comment by shepherdlewis000** [comment]
@rosenbergmichael I want to ensure that the app is responsive even on smaller phones. I think smallest mobile devices in general usage are at minimum 320px wide, such as the Moto G4. Chrome Developer Tools has a Device Toolbar/Device View to assist responsive design and the G4 is in the options for devices. Firefox also has a couple 320px wide devices including the iPhone 5.

When viewed 320px wide resolution, the site doesn't take full width of the screen. One step is to change usage of Bootstrap .container to .container-fluid which will make max-width of page be the display width. Then we'd need to have some check for device size and remove any left or right margin/padding so things can use the full width. The buttons could be changed to display block with .btn-block.
And more probably (checkboxes, font sizing...?)![Selection_202.png](https://images.zenhubusercontent.com/5ffb3867037534480b8094ae/538ba2ae-cc01-4a6d-b594-482205b588eb)

**Comment by shepherdlewis000** [comment]
On my phone, a Galaxy S8![Screenshot_20210528-095917_Brave.jpg](https://images.zenhubusercontent.com/5ffb3867037534480b8094ae/5f328751-1b7f-4471-87e1-0fe092dfb038)
